version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  setup:
    docker:
      - image: circleci/node:14.17.6-browsers
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
      - run: yarn --version

workflows:
  ci:
    - setup
